### ISSUE TITLE
训练结果很好，进行predict却全部都是检测不到，哪怕是训练的图片

### ISSUE THREAD

**Issue by Michael-FangJi** [bubbliiiing/yolov5-pytorch#23]
hello，谢谢作者的贡献，训练过程比原版要好一些。
但出现如标题的问题。
我训练好的权重评估loss有：loss0.013-val_loss0.013
但是模型无法成功检测任何图片目标，哪怕是训练样本。
请问可能是什么问题？

**Comment by Michael-FangJi** [comment]
这是个已知问题。所以close issue了。

**Comment by bubbliiiing** [comment]
OK~
